### ISSUE TITLE
Penetration test of Hybrid application

### ISSUE THREAD

**Issue by praveensinghinfo** [logicalhacking/DVHMA#1]
Hello Guys
This is just for asking some help from you and not an issue.
Please guide me how to do penetration test of any hybrid application.
If there is any tool / script or anything like that which is helpful for pentesting the hybrid apps ?

**Comment by praveensinghinfo** [comment]
Kindly Guide me through this ..

**Comment by tbela99** [comment]
try android virtual device + mitmproxy
